---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: aurora-custom
description: Mashup of Bazzite and Aurora-DX.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: bluefin/system_files/shared/usr/bin
        destination: /usr/bin
      - source: bluefin/system_files/shared/usr/libexec
        destination: /usr/libexec
      - source: bluefin/system_files/shared/usr/lib/tmpfiles.d
        destination: /usr/lib/tmpfiles.d
      - source: bluefin/system_files/shared/usr/share/ublue-os/bluefin-cli
        destination: /usr/share/ublue-os/bluefin-cli
      - source: bluefin/system_files/shared/usr/share/ublue-os/homebrew
        destination: /usr/share/ublue-os/homebrew
      - source: bluefin/system_files/shared/usr/share/ublue-os/quadlets
        destination: /usr/share/ublue-os/quadlets
      - source: bluefin/system_files/shared/usr/share/ublue-os/ublue-os.jsonc
        destination: /usr/share/ublue-os/ublue-os.jsonc
      - source: bluefin/system_files/kinoite/usr/bin
        destination: /usr/bin
      - source: bluefin/system_files/kinoite/usr/share/applications
        destination: /usr/share/applications
      - source: bluefin/system_files/kinoite/usr/share/kglobalaccel
        destination: /usr/share/kglobalaccel
      - source: bluefin/system_files/dx
        destination: /
      - source: files/shared
        destination: /
      - source: files/kinoite
        destination: /

# Install packages, flatpaks, and install extra software
  - from-file: packages.yml
  - from-file: extra_steps.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

